# SPDX-License-Identifier: GPL-3.0-or-later
name: Build
on:
  push:
    branches:
      - master
      - test-build
    tags:
      - release-*
jobs:
  build-linux:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: install
      run: >
        sudo apt install
        ninja-build
        freeglut3-dev
        libglew-dev
        libglm-dev
        libpng-dev
        libphysfs-dev
        libgtk-3-dev
    - name: configure
      run: |
        cmake --version
        mkdir build
        cd build
        cmake -G Ninja -DCMAKE_BUILD_TYPE=Release ..
    - name: build
      run: |
        cd build
        cmake --build . --target all
    - uses: actions/upload-artifact@master
      with:
        name: MyHumanoid-linux
        path: build
  build-windows:
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: install
      shell: bash
      run: >
        vcpkg install
        freeglut:x64-windows
        glew:x64-windows
        glm:x64-windows
        physfs:x64-windows
    - name: configure
      shell: bash
      run: |
        cmake --version
        mkdir build
        cd build
        cmake -G "Visual Studio 16 2019" -A x64 -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=C:/vcpkg/scripts/buildsystems/vcpkg.cmake ..
        ls
    - name: build
      shell: bash
      run: |
        cd build
        cmake --build . --target ALL_BUILD --config Release
        ls
        ls Release
    - name: package
      shell: bash
      run: |
        mkdir build-package
        cp build/Release/* build-package/
        cp build/MyHumanoid.data build-package/
        ls build-package
    - uses: actions/upload-artifact@master
      with:
        name: MyHumanoid-windows
        path: build-package
    - name: Pack Build
      shell: bash
      run: |
        zip -r MyHumanoid-windows-snapshot.zip build-package
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1.0.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Snapshot ${{ github.ref }}
        draft: true
        prerelease: true
    - name: Upload Release
      id: upload-release-asset
      uses: actions/upload-release-asset@v1.0.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./MyHumanoid-windows-snapshot.zip
        asset_name: MyHumanoid-windows-snapshot.zip
        asset_content_type: application/zip
